ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone_e164 VARCHAR(32);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
